{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-noop",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-noop-metadata-0.0.3.jar",
          "url": "kourier-noop-0.0.3.jar",
          "size": 4163,
          "sha512": "3af76ab5fbf74c62af347af56ba8e85824294f567b5df9941125e9db1d8a1fc414df9d5ca3576133eb422cc415babef047953fbff5185e640eb97aa77ad2014c",
          "sha256": "3b7a16ec1be664d7519a6f602544287ef84d4e1af2a2c2e946c179abb56f48a2",
          "sha1": "4e44ac675f892cde410cdcd1da0381fc6c486918",
          "md5": "2efdd4d3cf6fd0e317b75900351e1b2c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kourier-noop-kotlin-0.0.3-sources.jar",
          "url": "kourier-noop-0.0.3-sources.jar",
          "size": 4597,
          "sha512": "261ea0e33fe59e446bb547d78659b46b3714ab9a47e359b51e6e9ccb4e91fd806f38a48d55a2874bdfca83fa437eb7bdda94a665020235cfa5a788f8ba473fd1",
          "sha256": "97df1c2749c9d6108b122f3b9357f3650651929abd04657cc10e965564870e2d",
          "sha1": "c1e539a9fecb5da4f289288574f9f08d8ff6c969",
          "md5": "212960b71e926db071c3960bde4106ec"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-noop-android/0.0.3/kourier-noop-android-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-android",
        "version": "0.0.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-noop-android/0.0.3/kourier-noop-android-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-android",
        "version": "0.0.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-noop-android/0.0.3/kourier-noop-android-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-android",
        "version": "0.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iosarm64/0.0.3/kourier-noop-iosarm64-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iosarm64",
        "version": "0.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iosarm64/0.0.3/kourier-noop-iosarm64-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iosarm64",
        "version": "0.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iosarm64/0.0.3/kourier-noop-iosarm64-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iosarm64",
        "version": "0.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iossimulatorarm64/0.0.3/kourier-noop-iossimulatorarm64-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iossimulatorarm64",
        "version": "0.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iossimulatorarm64/0.0.3/kourier-noop-iossimulatorarm64-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iossimulatorarm64",
        "version": "0.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iossimulatorarm64/0.0.3/kourier-noop-iossimulatorarm64-0.0.3.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iossimulatorarm64",
        "version": "0.0.3"
      }
    }
  ]
}
