{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-storage",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-storage-metadata-0.0.6.jar",
          "url": "kourier-storage-0.0.6.jar",
          "size": 8583,
          "sha512": "44bef309aac7638956faacf5f09d0a19dfa24dbc6bb9213e56a440bd8a07489acb1766e54e844d3206fac34027370db2210327bb5f07a997f3f42408f68be90f",
          "sha256": "02f5c513b7b5ca2fd2406930d9f35e0d5232020fcbe6b135b7800dc8a5b23645",
          "sha1": "94f11ffe023c87c299c5749eed52d8941d8131bf",
          "md5": "100f8e6327bfd785a9134edf44e14095"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kourier-storage-kotlin-0.0.6-sources.jar",
          "url": "kourier-storage-0.0.6-sources.jar",
          "size": 9019,
          "sha512": "954582c73e9914037df9811a74963fcc6cecf652fe40ae77d39198817c9bc213bfe148709bf375a7ae0d0519ca87cf1ea404b6ce1d95afe02b5ba4e12a73fbd2",
          "sha256": "63509d7949073873caffec0092e5ff356c2409464abfbfc9fb9cc0a5bf9209ad",
          "sha1": "91bf224a74a4b24d4936c99e2fe9debd5a72124e",
          "md5": "516676b8067f05c0cad3507027f8cc43"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-storage-android/0.0.6/kourier-storage-android-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-android",
        "version": "0.0.6"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-storage-android/0.0.6/kourier-storage-android-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-android",
        "version": "0.0.6"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-storage-android/0.0.6/kourier-storage-android-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-android",
        "version": "0.0.6"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-storage-iosarm64/0.0.6/kourier-storage-iosarm64-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-iosarm64",
        "version": "0.0.6"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-storage-iosarm64/0.0.6/kourier-storage-iosarm64-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-iosarm64",
        "version": "0.0.6"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-storage-iosarm64/0.0.6/kourier-storage-iosarm64-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-iosarm64",
        "version": "0.0.6"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-storage-iossimulatorarm64/0.0.6/kourier-storage-iossimulatorarm64-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-iossimulatorarm64",
        "version": "0.0.6"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-storage-iossimulatorarm64/0.0.6/kourier-storage-iossimulatorarm64-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-iossimulatorarm64",
        "version": "0.0.6"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-storage-iossimulatorarm64/0.0.6/kourier-storage-iossimulatorarm64-0.0.6.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-storage-iossimulatorarm64",
        "version": "0.0.6"
      }
    }
  ]
}
