{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-interceptor-darwin/0.0.1/kourier-interceptor-darwin-0.0.1.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-interceptor-darwin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-darwin-iosSimulatorArm64Main-0.0.1.klib",
          "url": "kourier-interceptor-darwin-iossimulatorarm64-0.0.1.klib",
          "size": 25902,
          "sha512": "72f81448f58727f1af0f298367247026a070054860c6c7ee4ec0bc34db9da95b61e57db302df8825210b624c0e6e7235d38110b6d3b8605f61b6332c9bb0e373",
          "sha256": "974a8378467e1c63585520d24a596576ff9e1f45a817805594a5a79f87417c75",
          "sha1": "a8833b809660ca54f324b03ba9d5168df5c42f41",
          "md5": "b4b430bd5b28de4a012cb513fb3abade"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kourier-interceptor-darwin-iossimulatorarm64-0.0.1-sources.jar",
          "url": "kourier-interceptor-darwin-iossimulatorarm64-0.0.1-sources.jar",
          "size": 5294,
          "sha512": "0e7840d3e5bf124759050a6ed5124dda426cdb5a286a5b036f6b6ab60b0a97f50d74db71ca281f9bffacd7c31a13bb3d5542e8873d5b55cf32a9220798839559",
          "sha256": "cb1e3dc8417b1d5f619ebec9e33e2b667de18c80d7c09c08ea34d8e860a922a0",
          "sha1": "d628c446e5228ab89505036bfc4406271254701c",
          "md5": "06292b846192dac232ea10c23c91b88c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-darwin-iossimulatorarm64-0.0.1-metadata.jar",
          "url": "kourier-interceptor-darwin-iossimulatorarm64-0.0.1-metadata.jar",
          "size": 3983,
          "sha512": "7cb63d145f2e9b37f0e401d9426a6075f0957ef0f1dd734c8bb617c97f3f90a470bd7974de0668ad51d7f09b3df9023b665859a99b541ecb19d4938e99e5f8d1",
          "sha256": "a07d4d8c686bc1a715f507210a514a0849b8ae6a093bbdad92d13ef0e63866b9",
          "sha1": "bcae555861e951c4023b6aaa2ad01e54bc2e04be",
          "md5": "a9d0209308fe3736bbfbec7d0dead0e4"
        }
      ]
    }
  ]
}
