{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-noop/0.0.8/kourier-noop-0.0.8.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-noop",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-noop.aar",
          "url": "kourier-noop-android-0.0.8.aar",
          "size": 10985,
          "sha512": "43d7c3fdd7974123882b863d8187484c2d7cf7e78e7c5a8509f8258aa2308db644cd80b1620d0816fff21235bd4bfb0c70ac3792c7ae0e0f591c3a5d5f28c1de",
          "sha256": "6989aba4268b2814121cb3a6bc3597173c8ec059e0c6522d70ab86c36a72ceab",
          "sha1": "be1f16f94a11e56036e9ca055d3a5c3ec7f86f17",
          "md5": "fbc785eee5b8a0dc196a37f182ce5219"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-noop.aar",
          "url": "kourier-noop-android-0.0.8.aar",
          "size": 10985,
          "sha512": "43d7c3fdd7974123882b863d8187484c2d7cf7e78e7c5a8509f8258aa2308db644cd80b1620d0816fff21235bd4bfb0c70ac3792c7ae0e0f591c3a5d5f28c1de",
          "sha256": "6989aba4268b2814121cb3a6bc3597173c8ec059e0c6522d70ab86c36a72ceab",
          "sha1": "be1f16f94a11e56036e9ca055d3a5c3ec7f86f17",
          "md5": "fbc785eee5b8a0dc196a37f182ce5219"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-noop-android-0.0.8-sources.jar",
          "url": "kourier-noop-android-0.0.8-sources.jar",
          "size": 5056,
          "sha512": "b3d1f465744ba76d71c89bd004f47ccc5926f6a4a0723afbb148318c0105c4ddb320ef919c315cd6c453bec8f83b3d9a761ec313d6e5a674da8c8c223fff98b8",
          "sha256": "6c8e5228f77c76ce66109171037a485ceb67321704002d5621ce7d7d1d06060b",
          "sha1": "fe22ac2d67365f31f64a134644af380884b44bd8",
          "md5": "1b843e8e650bf4c7dacfd9f0121bc236"
        }
      ]
    }
  ]
}
