{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-ui/0.0.9/kourier-ui-0.0.9.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-ui",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.9.aar",
          "size": 555568,
          "sha512": "915b6f0a842431ebe372db96afc2a8a734a6e5977cd816f546905faecdaeef170fb940ecbc212296af2937af7ba7df453816fc89b596c592774d91ee400fbca2",
          "sha256": "7d12a7007e31370d5b43512bf885544de26e25c3a7cadc5f8f1663e82a6258e1",
          "sha1": "b25f69c8dbd524e2dd8ad636505df30dcc6327b9",
          "md5": "d65c577a6952f542cd5a5e4b9ff1a507"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.9.aar",
          "size": 555568,
          "sha512": "915b6f0a842431ebe372db96afc2a8a734a6e5977cd816f546905faecdaeef170fb940ecbc212296af2937af7ba7df453816fc89b596c592774d91ee400fbca2",
          "sha256": "7d12a7007e31370d5b43512bf885544de26e25c3a7cadc5f8f1663e82a6258e1",
          "sha1": "b25f69c8dbd524e2dd8ad636505df30dcc6327b9",
          "md5": "d65c577a6952f542cd5a5e4b9ff1a507"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-ui-android-0.0.9-sources.jar",
          "url": "kourier-ui-android-0.0.9-sources.jar",
          "size": 118661,
          "sha512": "2bafba94a17e7a4535cd68680673cf8400d8442f115565e58fa71aed637f4a11f354ff2ed0916efcddf66c6726f20470b78bdc840285c8766a0d017fc8b34963",
          "sha256": "5c19ede19ff8e1722da2a35ddc15705d7bb5c191bdee9a2cb44f82885d431541",
          "sha1": "22615d43a59602408eb7db2066f9868b81607648",
          "md5": "0d23b36ef36f97a2accee66012703306"
        }
      ]
    }
  ]
}
