{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-ui",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui-metadata-0.0.7.jar",
          "url": "kourier-ui-0.0.7.jar",
          "size": 90991,
          "sha512": "00063a911650a22ac8b2a2c8ed1390bc5c72db7dae6535b921aee883e4b9014db9e68850d07c2b53d0dac40f3d32d1446e32862ed05a40adf388b771a2353093",
          "sha256": "34c56166aaa593179627f1104d7498f5cd7ab6bb1774faab39f22e99518593c0",
          "sha1": "6702bee1ca315c3561faf74de3f3a3f6b0fae9ea",
          "md5": "8f7c25f41ebe059262ad437af21775e0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kourier-ui-kotlin-0.0.7-sources.jar",
          "url": "kourier-ui-0.0.7-sources.jar",
          "size": 118430,
          "sha512": "6d3a0568ad0bfb9bbcdef6d8ef7197f2c0208334f2965c0ca1f209c56e43f672161b60ecacbbbe411d2f9130fa7691a9695d53a7958c9de44c9ef8495ef494b9",
          "sha256": "1c4eb3d15a1e460ccbf16c2e96f757cb49ec147f87f219d40498fdf02f7a7914",
          "sha1": "3e9c7b66ff2dd9396f339daaabddbaeeecad5003",
          "md5": "74e12d87d5d3f613a5173d783eb67f28"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-ui-android/0.0.7/kourier-ui-android-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-android",
        "version": "0.0.7"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-ui-android/0.0.7/kourier-ui-android-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-android",
        "version": "0.0.7"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-ui-android/0.0.7/kourier-ui-android-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-android",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.7/kourier-ui-iosarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.7/kourier-ui-iosarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.7/kourier-ui-iosarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.7/kourier-ui-iosarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.7/kourier-ui-iossimulatorarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.7/kourier-ui-iossimulatorarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.7/kourier-ui-iossimulatorarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.7"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.7/kourier-ui-iossimulatorarm64-0.0.7.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.7"
      }
    }
  ]
}
