{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-ui/0.0.5/kourier-ui-0.0.5.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-ui",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.5.aar",
          "size": 551971,
          "sha512": "2fc5de3d0e72f475eca72ac3ee634dab8cb48d36781e96fde108e2796a06acc2fe018a872fb927178494d177530519a1b415c3878ca83bb07484061b879bd6f0",
          "sha256": "8056ab707cfe745522a5d0e0908c48005d988925a399b1634190a720f02f5131",
          "sha1": "f22496edf215cbe2bd080cebe1caed7e9df15995",
          "md5": "9137300395da76bafebbd4457273621e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.5.aar",
          "size": 551971,
          "sha512": "2fc5de3d0e72f475eca72ac3ee634dab8cb48d36781e96fde108e2796a06acc2fe018a872fb927178494d177530519a1b415c3878ca83bb07484061b879bd6f0",
          "sha256": "8056ab707cfe745522a5d0e0908c48005d988925a399b1634190a720f02f5131",
          "sha1": "f22496edf215cbe2bd080cebe1caed7e9df15995",
          "md5": "9137300395da76bafebbd4457273621e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-ui-android-0.0.5-sources.jar",
          "url": "kourier-ui-android-0.0.5-sources.jar",
          "size": 117987,
          "sha512": "88144b199623bd1e0eac1fc81eca6c95d3bc04f24d0af91ee22cd5150f26cf1b532ce01bfb5a9a9c3ecf9ff5939faefa861682ee6002a486832ceb099fc635a6",
          "sha256": "d8cbedf9aac6bed28524fe33497df67f6c66a4810e788b195d053a1ff771d5ad",
          "sha1": "d31da7dedf14044de87f2a65bd9710bf7ed6b54f",
          "md5": "b05041f11728b7ae4ae7f0e009bce96d"
        }
      ]
    }
  ]
}
