{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-android",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-okhttp",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-ktor",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-android-0.0.2.aar",
          "url": "kourier-android-0.0.2.aar",
          "size": 111555,
          "sha512": "cc529fa3cfa1d782196c7d6a5b8cc23bf27644e37dc7a98104b56362073b2b36c56fe4511ddf1d3f7d0a3ab049c0cbffc80114fe10ec4706bec8b7cbbe699530",
          "sha256": "6d9dcdfe0ca203d59ae75ca2c8167c23dc75b7941c43902cf8d61141ff9b0238",
          "sha1": "7b87987e5e1c488499fbd2542df0039901645d60",
          "md5": "9938459130ad0fcfef52994a63561a05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-ui",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-okhttp",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-ktor",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-android-0.0.2.aar",
          "url": "kourier-android-0.0.2.aar",
          "size": 111555,
          "sha512": "cc529fa3cfa1d782196c7d6a5b8cc23bf27644e37dc7a98104b56362073b2b36c56fe4511ddf1d3f7d0a3ab049c0cbffc80114fe10ec4706bec8b7cbbe699530",
          "sha256": "6d9dcdfe0ca203d59ae75ca2c8167c23dc75b7941c43902cf8d61141ff9b0238",
          "sha1": "7b87987e5e1c488499fbd2542df0039901645d60",
          "md5": "9938459130ad0fcfef52994a63561a05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kourier-android-0.0.2-sources.jar",
          "url": "kourier-android-0.0.2-sources.jar",
          "size": 4426,
          "sha512": "fc7347e55b883986e148de9401f5b17086c8a8be9ac1ac70077f291aa1c752af0fe3162f20824d27dccef60e687dee316f97d5e276fd5f82b583f3ecb3dc1303",
          "sha256": "55bf01876fd49e85fe33d1633ca61391c5e7a7d4375d325fa9176a6fee2f0ed2",
          "sha1": "fceb7b82a8d86c96d0f61b2bb5d8143975f1243c",
          "md5": "8953fc6f64118e8b08843decdcf51678"
        }
      ]
    }
  ]
}
