{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-ui/0.0.7/kourier-ui-0.0.7.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-ui",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.7.aar",
          "size": 552184,
          "sha512": "2fde4cb78cb68ac38487a770f88f25fecfc6c783cff20881d587b7c5d6219f861c85bb0840ac993a1ddcb13dcfb1392c3670908a7026938fc5ed9095e414c2fe",
          "sha256": "3bb58365c8f44bdede72ab07c7e6955538f899fd8edb4eb088c6d15aa64b1f7b",
          "sha1": "1be3fade364dcd48507ed450aa4f50f4238fed7d",
          "md5": "c0ec54de459b80e32100e76654f406b4"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.7.aar",
          "size": 552184,
          "sha512": "2fde4cb78cb68ac38487a770f88f25fecfc6c783cff20881d587b7c5d6219f861c85bb0840ac993a1ddcb13dcfb1392c3670908a7026938fc5ed9095e414c2fe",
          "sha256": "3bb58365c8f44bdede72ab07c7e6955538f899fd8edb4eb088c6d15aa64b1f7b",
          "sha1": "1be3fade364dcd48507ed450aa4f50f4238fed7d",
          "md5": "c0ec54de459b80e32100e76654f406b4"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-ui-android-0.0.7-sources.jar",
          "url": "kourier-ui-android-0.0.7-sources.jar",
          "size": 118318,
          "sha512": "3620396b0e7698079d73a3774956a1c2c69fa50785cb3339805d319ffba6e847027112a7e69434cea3b01bb9c33ed0ce0912ef32d821cbadbb2ea2e21e536177",
          "sha256": "0f46bb19e6cbc8fce0a83fd6b8bab759724f4a12f6daf06bfa40b555feee400d",
          "sha1": "738c1402d241829d62904587c4c15886b18d01ec",
          "md5": "09a0a36844aa5be67236d7251a19867f"
        }
      ]
    }
  ]
}
