{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-ui",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui-metadata-0.0.9.jar",
          "url": "kourier-ui-0.0.9.jar",
          "size": 91085,
          "sha512": "962e82cd8b6c59edbc3bda7cb1c41d3becc5f280acdcfcae1eb34ff4f730c1193c613ee716becea7e477760f6cbcbddf0ba44704289f54c41134215c1b6500d1",
          "sha256": "237178afa8f5500b6985844e266a8123fb01f726894a31c8340d1f5cc57ec57e",
          "sha1": "63ca7f9806ba3b34fb972ee31af26d59ab886021",
          "md5": "e115b13b405fa9685ebf2c8923f686a8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kourier-ui-kotlin-0.0.9-sources.jar",
          "url": "kourier-ui-0.0.9-sources.jar",
          "size": 119363,
          "sha512": "cd0ef22f3748e77a1c330b5601fb7245e2912e8e8e7439760673604144944f2ca25da18e0faf2b31d5a5e97dd9fc84e7d299a5c5a46f8c70a3182d4a4f9cdf0d",
          "sha256": "88d9261e581c1c0d1806146d79a09923b5c380a7a57e1c048f4b3dd4ed2639d9",
          "sha1": "a2cc9ce68e59423e8e3791b154ac3110f0b66da2",
          "md5": "82788364960297a66fbdf269c54ac313"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-ui-android/0.0.9/kourier-ui-android-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-android",
        "version": "0.0.9"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-ui-android/0.0.9/kourier-ui-android-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-android",
        "version": "0.0.9"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-ui-android/0.0.9/kourier-ui-android-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-android",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.9/kourier-ui-iosarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.9/kourier-ui-iosarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.9/kourier-ui-iosarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iosarm64/0.0.9/kourier-ui-iosarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iosarm64",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.9/kourier-ui-iossimulatorarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.9/kourier-ui-iossimulatorarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.9/kourier-ui-iossimulatorarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.9"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-ui-iossimulatorarm64/0.0.9/kourier-ui-iossimulatorarm64-0.0.9.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-ui-iossimulatorarm64",
        "version": "0.0.9"
      }
    }
  ]
}
