{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-interceptor-darwin/0.0.1/kourier-interceptor-darwin-0.0.1.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-interceptor-darwin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-darwin-iosArm64Main-0.0.1.klib",
          "url": "kourier-interceptor-darwin-iosarm64-0.0.1.klib",
          "size": 25835,
          "sha512": "a191c33e73cfb305e0d1dea4d561914159367cb9889c214890d342d118279a0aebe3738eabd8d5f046384ed2999d56b9ee4d4862ff780e8b89df16c4eb61265a",
          "sha256": "029095006a2f210e695325780982aba963e373706bf2b8a54351c26118293399",
          "sha1": "e044bcdf073874b40e021072c72ad43aba80de12",
          "md5": "d523040eb9fef85d3baddaa85cb1e4df"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kourier-interceptor-darwin-iosarm64-0.0.1-sources.jar",
          "url": "kourier-interceptor-darwin-iosarm64-0.0.1-sources.jar",
          "size": 5294,
          "sha512": "0e7840d3e5bf124759050a6ed5124dda426cdb5a286a5b036f6b6ab60b0a97f50d74db71ca281f9bffacd7c31a13bb3d5542e8873d5b55cf32a9220798839559",
          "sha256": "cb1e3dc8417b1d5f619ebec9e33e2b667de18c80d7c09c08ea34d8e860a922a0",
          "sha1": "d628c446e5228ab89505036bfc4406271254701c",
          "md5": "06292b846192dac232ea10c23c91b88c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-darwin-iosarm64-0.0.1-metadata.jar",
          "url": "kourier-interceptor-darwin-iosarm64-0.0.1-metadata.jar",
          "size": 3983,
          "sha512": "7cb63d145f2e9b37f0e401d9426a6075f0957ef0f1dd734c8bb617c97f3f90a470bd7974de0668ad51d7f09b3df9023b665859a99b541ecb19d4938e99e5f8d1",
          "sha256": "a07d4d8c686bc1a715f507210a514a0849b8ae6a093bbdad92d13ef0e63866b9",
          "sha1": "bcae555861e951c4023b6aaa2ad01e54bc2e04be",
          "md5": "a9d0209308fe3736bbfbec7d0dead0e4"
        }
      ]
    }
  ]
}
