{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-core",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-core-metadata-0.0.5.jar",
          "url": "kourier-core-0.0.5.jar",
          "size": 23651,
          "sha512": "8b84ade40a227718e17551b713fbcc56188459cd525227feade0714094103522a9d191ac81c3229d01010c6743a622ad4f831f2580ae3ebf3af1656c31c30e5c",
          "sha256": "f60847f55d046c709e3265d087aac5b5a8d4086864ddd65664a1b5812903d7e4",
          "sha1": "bf02f94bc8252d01fdad47edf41b53eeffc78c0f",
          "md5": "b7855568590cd43dbdf5ed1a58a88ecb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kourier-core-kotlin-0.0.5-sources.jar",
          "url": "kourier-core-0.0.5-sources.jar",
          "size": 20568,
          "sha512": "9c79c6fea81d21e2f29ee867dd2192e69e3e5dd197b27226b3d0992b6e748fcf0629def9a044a5214ba2fa82da943ffb5f7376b8de3c1af9ff10a78176822b43",
          "sha256": "49adb29699366d69817138d62335f2f0858b3eac43c4264a6ee37b7e67da14cf",
          "sha1": "beb4b6f3933862a1664b9d15008c338c303d9477",
          "md5": "c365eb86e2b57f050537217b66abd215"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-core-android/0.0.5/kourier-core-android-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-android",
        "version": "0.0.5"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-core-android/0.0.5/kourier-core-android-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-android",
        "version": "0.0.5"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-core-android/0.0.5/kourier-core-android-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-android",
        "version": "0.0.5"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iosarm64/0.0.5/kourier-core-iosarm64-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iosarm64",
        "version": "0.0.5"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iosarm64/0.0.5/kourier-core-iosarm64-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iosarm64",
        "version": "0.0.5"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iosarm64/0.0.5/kourier-core-iosarm64-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iosarm64",
        "version": "0.0.5"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iossimulatorarm64/0.0.5/kourier-core-iossimulatorarm64-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iossimulatorarm64",
        "version": "0.0.5"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iossimulatorarm64/0.0.5/kourier-core-iossimulatorarm64-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iossimulatorarm64",
        "version": "0.0.5"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-core-iossimulatorarm64/0.0.5/kourier-core-iossimulatorarm64-0.0.5.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-core-iossimulatorarm64",
        "version": "0.0.5"
      }
    }
  ]
}
