{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-core/0.0.1/kourier-core-0.0.1.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-core.aar",
          "url": "kourier-core-android-0.0.1.aar",
          "size": 210320,
          "sha512": "dc15f4d9a012ac8946ee86c0ee49a150d1900c77658d063a67014aa22220d8584a9906f5a469666643255cbac4da4bdd289858b2a83bddebf39ef4774c83229e",
          "sha256": "0e9ec938e1903db2da7fda2fb57369545e3ffa4801f7d5786755721c78bc0c5f",
          "sha1": "dd1b1a2df030380f9c99bcec2f0fa606099bbef3",
          "md5": "bc3608637c62e55f401175032422b79f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-core.aar",
          "url": "kourier-core-android-0.0.1.aar",
          "size": 210320,
          "sha512": "dc15f4d9a012ac8946ee86c0ee49a150d1900c77658d063a67014aa22220d8584a9906f5a469666643255cbac4da4bdd289858b2a83bddebf39ef4774c83229e",
          "sha256": "0e9ec938e1903db2da7fda2fb57369545e3ffa4801f7d5786755721c78bc0c5f",
          "sha1": "dd1b1a2df030380f9c99bcec2f0fa606099bbef3",
          "md5": "bc3608637c62e55f401175032422b79f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-core-android-0.0.1-sources.jar",
          "url": "kourier-core-android-0.0.1-sources.jar",
          "size": 20315,
          "sha512": "7b360da93d62de17af9f8f8c26f8011a6e5a8af03e24bbc6efe40cce8c55ccf61b9aa096d81d44833658cc719d511eb49e67a280afc8ac53c00e3cc2884c9b8f",
          "sha256": "879ed91ffe4fa74ccc828a9b6c675b490bed7abcbb01c72e361224f858645f61",
          "sha1": "ab0c119efcd1fbc9dc6f6a33a1f8fe5a1f2e0d29",
          "md5": "17b45e3e17e033bf994db6281c70aadd"
        }
      ]
    }
  ]
}
