{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-core/0.0.2/kourier-core-0.0.2.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-core",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-core.aar",
          "url": "kourier-core-android-0.0.2.aar",
          "size": 210259,
          "sha512": "224c69cc2b2488f6aa0402c488b87393deec246f46448abe4a2fedeedb30991fbdb3e0c31491a7ddda3373d919068a3b2313f8ede3b2946116d824b939a5a4a1",
          "sha256": "4e463e53ea54ea99272b53840d47c8354f269e881504e1431fa6670a150b1541",
          "sha1": "e4b28e4fa7f8b7521bc5279884c7ff36838cb422",
          "md5": "f8c39e0b5dbe34d5e8902e70b3a24adf"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-core.aar",
          "url": "kourier-core-android-0.0.2.aar",
          "size": 210259,
          "sha512": "224c69cc2b2488f6aa0402c488b87393deec246f46448abe4a2fedeedb30991fbdb3e0c31491a7ddda3373d919068a3b2313f8ede3b2946116d824b939a5a4a1",
          "sha256": "4e463e53ea54ea99272b53840d47c8354f269e881504e1431fa6670a150b1541",
          "sha1": "e4b28e4fa7f8b7521bc5279884c7ff36838cb422",
          "md5": "f8c39e0b5dbe34d5e8902e70b3a24adf"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-core-android-0.0.2-sources.jar",
          "url": "kourier-core-android-0.0.2-sources.jar",
          "size": 20388,
          "sha512": "f3af2f199d3312bbcb7bd943a07c6438dc65cbd7d7ab658c56bdb4a2363b9c7bc6fc8f8874d71aee8532d1b6fa59b2683b25c8060dd02033b7550d21992ea71d",
          "sha256": "7a68bdc943aa39646c85fda94f02b14d83085a6e788d14a98345c048300718f9",
          "sha1": "52e35273cce8b9c839f481a3b21bf662fa41fc41",
          "md5": "ac864684a95eaf87dfc140533c2b9c19"
        }
      ]
    }
  ]
}
