{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-ui/0.0.6/kourier-ui-0.0.6.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-ui",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.6.aar",
          "size": 552482,
          "sha512": "264fd1f0b61f502d4fbdc90c0fba8122e471794d12c2a4301d40e73f91f17277f68b5cd66ed27da5f7addfcaca49d94dd3c7402877ab301ce97cffdda657a4d6",
          "sha256": "09d03783217323317889043e2b50c9b1e9b2bc14351642ba6ef750757429746e",
          "sha1": "ade5de52125e6ac854b187ef2da336935bc5d95a",
          "md5": "1000d9883bf05d7fdf9164751cc720ef"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-ui.aar",
          "url": "kourier-ui-android-0.0.6.aar",
          "size": 552482,
          "sha512": "264fd1f0b61f502d4fbdc90c0fba8122e471794d12c2a4301d40e73f91f17277f68b5cd66ed27da5f7addfcaca49d94dd3c7402877ab301ce97cffdda657a4d6",
          "sha256": "09d03783217323317889043e2b50c9b1e9b2bc14351642ba6ef750757429746e",
          "sha1": "ade5de52125e6ac854b187ef2da336935bc5d95a",
          "md5": "1000d9883bf05d7fdf9164751cc720ef"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-ui-android-0.0.6-sources.jar",
          "url": "kourier-ui-android-0.0.6-sources.jar",
          "size": 118265,
          "sha512": "0c9047903ea9eae62858e1bf565ad661905f9fc748df353db2d314aef2922cb7278994fbe0157cdf99b0d985cf89b1d41869fb88b66a1900d76c28585cd93a90",
          "sha256": "82889fba81462dbb067fcc25f24906b6530373b427fd5f126d58743c070c8056",
          "sha1": "468191945f246937b39579ed024cac7ae410bcf2",
          "md5": "587d4d248d5b3f78a4389d1fac6ede6b"
        }
      ]
    }
  ]
}
