{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-storage/0.0.1/kourier-storage-0.0.1.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-storage",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-storage-iosArm64Main-0.0.1.klib",
          "url": "kourier-storage-iosarm64-0.0.1.klib",
          "size": 37982,
          "sha512": "14220b7dd017313f3a1500a6eae813ac2d9d48a90f723dffc3dafbbcadb839ce5401fd37e3a25f97aca60399317d0b31e7099fcf959c20d69291b1d19f20726c",
          "sha256": "0644dfcc9756254a35c98bf73a9277fc781b92455c9b325901dc9b657e6d72a2",
          "sha1": "2877fe5330d2f0db316573e616fc9fc07a7552ff",
          "md5": "0a789a603748dcf3794d8895cd3b56e0"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kourier-storage-iosarm64-0.0.1-sources.jar",
          "url": "kourier-storage-iosarm64-0.0.1-sources.jar",
          "size": 9019,
          "sha512": "b940d91990280b5a4957dfa72f2952bf2985a93cf6698ce7cfe46be5813daa6968520a4c8f147add51f7429721a7f62955801eb8176da0b3eb48c0837442020c",
          "sha256": "e75ff5fc07542ccf1c6924d7a1d130f17862998883641649ddc0c36e548dd604",
          "sha1": "12174708c082000570859d132549f239effb6902",
          "md5": "47c71c37d3c4a82c4d325c6e530117fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-storage-iosarm64-0.0.1-metadata.jar",
          "url": "kourier-storage-iosarm64-0.0.1-metadata.jar",
          "size": 2498,
          "sha512": "3cacb87d2cb883092f6222239a594353b9d36a1fadb6ff59ed8d84e03eddeafe61b9494696535d354c98ad88544f0ccc25d027af75c34cea1c245e4233c4204e",
          "sha256": "b87ec52ee84a2625eb13b7c1473a5c945cd9a8b233ef74785f76d73a9f989d67",
          "sha1": "312d9dcc847355c6c5661899331e00174a36206b",
          "md5": "c8e55940d6c38601745df18b55c8dfce"
        }
      ]
    }
  ]
}
