{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-interceptor-ktor/0.0.10/kourier-interceptor-ktor-0.0.10.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-interceptor-ktor",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-ktor.aar",
          "url": "kourier-interceptor-ktor-android-0.0.10.aar",
          "size": 17220,
          "sha512": "62bccd45d698cc3fb667b82ba52316426d7b887d9f294beb33368d5c49dbeaac90aa726cefea2d901a70addeb7192ab2910c6ce7ee8afd735ff2cc3f4cdb29ca",
          "sha256": "30d0e81c4e462aec404a8428010b0c554eab6678077041fc9e5976c45fb98d6a",
          "sha1": "94a51b7068af4e7621175c149f53c42e617b382a",
          "md5": "8c020d2d0a5d33352221dc605c31d070"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-ktor.aar",
          "url": "kourier-interceptor-ktor-android-0.0.10.aar",
          "size": 17220,
          "sha512": "62bccd45d698cc3fb667b82ba52316426d7b887d9f294beb33368d5c49dbeaac90aa726cefea2d901a70addeb7192ab2910c6ce7ee8afd735ff2cc3f4cdb29ca",
          "sha256": "30d0e81c4e462aec404a8428010b0c554eab6678077041fc9e5976c45fb98d6a",
          "sha1": "94a51b7068af4e7621175c149f53c42e617b382a",
          "md5": "8c020d2d0a5d33352221dc605c31d070"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kourier-interceptor-ktor-android-0.0.10-sources.jar",
          "url": "kourier-interceptor-ktor-android-0.0.10-sources.jar",
          "size": 3228,
          "sha512": "9639b7d474cab70cd4954b0cc7ecd9c454f3039e28b4f3ac196fb59ba01c16a64874c971797baee44eac84fe99e6e2aa3974ae188f8a4d08922f6e2685577afd",
          "sha256": "0595e810b2e6f4ba98887fdd087994579c8dfd94693312f1e935918f140b7783",
          "sha1": "2a1d7fc515179e3345dc24107aed4c86e46713c1",
          "md5": "e26035ce659c944eb79ebe4d2baa909a"
        }
      ]
    }
  ]
}
