{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-noop/0.0.1/kourier-noop-0.0.1.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-noop",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-noop-iosArm64Main-0.0.1.klib",
          "url": "kourier-noop-iosarm64-0.0.1.klib",
          "size": 12243,
          "sha512": "2662e25db4d644e037086455d0229d676528ecad3160a85fc939df7fc9acdad11117600e5488085295cdff5ce319b3efe44cb9e9bd90609babc3a744967e2e52",
          "sha256": "b36c5a17be2d32490526d2de5f2f3ef9dd8ee6001bb2c904bfd6bcde4d00946a",
          "sha1": "d3cfac69d660956df2ee1f5f06cda843d97b0c9d",
          "md5": "111dddde8ae5f55cf48e2ca09403bf38"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kourier-noop-iosarm64-0.0.1-sources.jar",
          "url": "kourier-noop-iosarm64-0.0.1-sources.jar",
          "size": 4516,
          "sha512": "bd09b10b1cbe794b1d553bc95afaa1ee1ada01adfac2dc6d608539d17df95c3f5d61af51a7e538f2388b9e7da4951ad8c276ea7764222ccb9e9d3c256d4713d3",
          "sha256": "afbfe4cc6d98f6784a17f66281fc4ecf5343067232b919f533356849c0494934",
          "sha1": "2a1ad3786300c5f34d9cac9e1d1bc9a1810af95b",
          "md5": "af76eb3dfea3c46ad5833329bcbcd7f2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-noop-iosarm64-0.0.1-metadata.jar",
          "url": "kourier-noop-iosarm64-0.0.1-metadata.jar",
          "size": 3355,
          "sha512": "a64aef32597edf6d2ebcabaac112de8d81ae800bb0fc3a1ee88ec2b1c46850bf5d0d0637469e683aa1d591b5cbcada3aa6dfcf3a9319bb42734e53517fc0a26f",
          "sha256": "4570ec63b934719a5baee27bf6d028490b2d73bec80424269a92dfb81c5a02a2",
          "sha1": "d959967cdfbc8674e628683688b7653c564ab6af",
          "md5": "6f10a250f4fdb49b4962a0d0018e0614"
        }
      ]
    }
  ]
}
