{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-android",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-okhttp",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-ktor",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-android-0.0.6.aar",
          "url": "kourier-android-0.0.6.aar",
          "size": 90616,
          "sha512": "6353633e169f141333d740a02a3fe781e78bb3ea3d0b7e38206860e98216ce0a8e1eb0367026663063f0ec3fa2562269576e26b710a57065745ddd1caa4ca4dc",
          "sha256": "cc795f8e9a48a570ae39e7bd1a11bd56f48a640d2873c525439a05c9b30a31c1",
          "sha1": "c069433e2ece81a7260d2ef0a76a2db81bcf32cc",
          "md5": "75a80cf60c28a4016590c861ae45c63a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-storage",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-ui",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-okhttp",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-interceptor-ktor",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-android-0.0.6.aar",
          "url": "kourier-android-0.0.6.aar",
          "size": 90616,
          "sha512": "6353633e169f141333d740a02a3fe781e78bb3ea3d0b7e38206860e98216ce0a8e1eb0367026663063f0ec3fa2562269576e26b710a57065745ddd1caa4ca4dc",
          "sha256": "cc795f8e9a48a570ae39e7bd1a11bd56f48a640d2873c525439a05c9b30a31c1",
          "sha1": "c069433e2ece81a7260d2ef0a76a2db81bcf32cc",
          "md5": "75a80cf60c28a4016590c861ae45c63a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kourier-android-0.0.6-sources.jar",
          "url": "kourier-android-0.0.6-sources.jar",
          "size": 4426,
          "sha512": "fc7347e55b883986e148de9401f5b17086c8a8be9ac1ac70077f291aa1c752af0fe3162f20824d27dccef60e687dee316f97d5e276fd5f82b583f3ecb3dc1303",
          "sha256": "55bf01876fd49e85fe33d1633ca61391c5e7a7d4375d325fa9176a6fee2f0ed2",
          "sha1": "fceb7b82a8d86c96d0f61b2bb5d8143975f1243c",
          "md5": "8953fc6f64118e8b08843decdcf51678"
        }
      ]
    }
  ]
}
