{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kourier-interceptor-ktor/0.0.1/kourier-interceptor-ktor-0.0.1.module",
    "group": "dev.shushant.kourier",
    "module": "kourier-interceptor-ktor",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-ktor-iosSimulatorArm64Main-0.0.1.klib",
          "url": "kourier-interceptor-ktor-iossimulatorarm64-0.0.1.klib",
          "size": 16008,
          "sha512": "376de76ec1e35155744ad3b7bc5f186a28aa8286ebac70b59fccd178a89cd10b818b11395abf857e2b9520a416bde3ca274d1459a49d7dea690f64742f960a33",
          "sha256": "6c8ee8e4e62a8351d983445fc58a88eb594bd6dda7affd4a32fe4a0f0d8cbf34",
          "sha1": "fabede1a42e901ce5b07c07c55f0fa4f3f282808",
          "md5": "8e4329ca94f360d6b071a14bbe75a8b7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kourier-interceptor-ktor-iossimulatorarm64-0.0.1-sources.jar",
          "url": "kourier-interceptor-ktor-iossimulatorarm64-0.0.1-sources.jar",
          "size": 2994,
          "sha512": "fb2ee07f42e2b12906be2285ec542297c808dfdeb7c91cdb080137fba24b46e0886cb960bc21be88d1473e28eff8cde6cd3223725518a6fd78bccc91116fd5d8",
          "sha256": "3598f8f8757185addaa80b40b6412d5dfcb202341cae451d7a5391f4ac465ea3",
          "sha1": "7f51792380390e7d73849db653751c2fbcc07a59",
          "md5": "0ea49ab6f60237bc347139921a3aa05d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "dev.shushant.kourier",
          "module": "kourier-core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-interceptor-ktor-iossimulatorarm64-0.0.1-metadata.jar",
          "url": "kourier-interceptor-ktor-iossimulatorarm64-0.0.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
