{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.shushant.kourier",
    "module": "kourier-noop",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kourier-noop-metadata-0.0.1.jar",
          "url": "kourier-noop-0.0.1.jar",
          "size": 4121,
          "sha512": "f6344914314b7439293d079675f1da158c9d15368080d5d25461d20edf5d832712a2caf78b382d2f962da7e7ff55126545b1fe68b97c2d08c1d56b1ebca6bb94",
          "sha256": "df463317b5edb527f1fd74e561158b8cf36b61f4ea001afd4c6da846cbe4a0fa",
          "sha1": "7ec7977e711d19bd8ba8ead24e7e92b053b91a16",
          "md5": "6ac2bfdda640bb1a008868ecbdcac1bb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kourier-noop-kotlin-0.0.1-sources.jar",
          "url": "kourier-noop-0.0.1-sources.jar",
          "size": 4516,
          "sha512": "c7bf5a3d3080a61828d2feb7189860246cb14a193d2b2d3ae3a4aeba51f813ddc4c65c5a2a25121e8abf3e92c747354f646d22b7f0afc89896a27f9c31c99dc4",
          "sha256": "f60cfbfc55dc88795879029f122dc2fe017a68068f6305afc65b9fc35bd3c28d",
          "sha1": "421178f9f1cee8da3a145104e8a1ff4dfb5d1625",
          "md5": "cefc582cb41cf67b941a8271856ec9e8"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-noop-android/0.0.1/kourier-noop-android-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-noop-android/0.0.1/kourier-noop-android-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kourier-noop-android/0.0.1/kourier-noop-android-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iosarm64/0.0.1/kourier-noop-iosarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iosarm64/0.0.1/kourier-noop-iosarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iosarm64/0.0.1/kourier-noop-iosarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iossimulatorarm64/0.0.1/kourier-noop-iossimulatorarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iossimulatorarm64/0.0.1/kourier-noop-iossimulatorarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kourier-noop-iossimulatorarm64/0.0.1/kourier-noop-iossimulatorarm64-0.0.1.module",
        "group": "dev.shushant.kourier",
        "module": "kourier-noop-iossimulatorarm64",
        "version": "0.0.1"
      }
    }
  ]
}
